language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov

notifications:
  webhooks: https://coveralls.io/webhook?repo_token=B5WcLFBsh1blwvKHipdeekzC1JxR1qhCo

script: 
  - coverage run -m unittest discover && coverage report
  
after_success: 
  - coveralls
  - codecov

