language: python
python:
  - "3.6"
postgres:
  adapter: postgresql
  database: test_db

services:
  - postgresql
 
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov

notifications:
  webhooks: https://coveralls.io/webhook?repo_token=B5WcLFBsh1blwvKHipdeekzC1JxR1qhCo

script: 
  - coverage run -m unittest discover && coverage report
  
after_success: 
  - coveralls
  - codecov

env:
 - DB=postgres

before_script:
 - psql -c "CREATE DATABASE test_db;" -U postgres
